version: '3.8'

services:
  redis-db-dev:
    container_name: "redis-db-dev"
    hostname: "redis-db-dev"
    image: redis:alpine
    command: /bin/ash -c "redis-server --requirepass ${REDIS_PASSWORD} --port 6380"
    env_file:
      - ./.env
    restart: always
    ports:
      - ${REDIS_PORT}:6380
    volumes:
      - ./db/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  redis-db-test:
    container_name: "redis-db-test"
    hostname: "redis-db-test"
    image: redis:alpine
    env_file:
      - ./.env
    restart: always
    ports:
      - ${REDIS_TEST_PORT}:6377
    command: /bin/ash -c "redis-server --port 6377"
    depends_on:
      - redis-db-dev