version: '3.8'

services:

  app-dev:
    container_name: "app-dev"
    env_file:
      - ./.env
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:5000
    depends_on:
      - redis-db-dev

  redis-db-dev:
    container_name: "redis-db-dev"
    hostname: "redis-db-dev"
    image: redis:alpine
    command: /bin/ash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file:
      - ./.env
    restart: always
    ports:
      - ${EXT_REDIS_POR}:6379
    volumes:
      - ./db/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G